services:
  manga-server:
    build: .
    container_name: manga_server
    restart: unless-stopped
    
    # CRITICAL: This gives the container permission to control the Pi's hardware
    privileged: true
    network_mode: "host" 

    # ports:
      # - "8000:8000"
    
    environment:
      - DATA_DIR=/app/data
      # Tells our code we are on real hardware
      - MOCK_MODE=false
      
    volumes:
      # 1. Your Data
      - ./data:/app/data
      - ./app:/app/app
      
      # 2. System Control Passthrough (Required for hostnamectl & nmcli)
      - /var/run/dbus:/var/run/dbus
      - /var/run/systemd:/var/run/systemd
      - /etc/localtime:/etc/localtime:ro
      
      # 3. Persistence for NetworkManager connections
      - /etc/NetworkManager/system-connections:/etc/NetworkManager/system-connections